services:
  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: frontend
    ports:
      - 5000:5000
    environment:
      - BACKEND_URL=http://backend:5001/
    networks:
      - shared_network
  
  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend
    ports:
      - 5001:5001
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network
    external: true
